default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5
  username: ubuntu
  password: password

development:
  <<: *default
  database: ubuntu

test:
  <<: *default
  database: ubuntu

production:
  <<: *default
  encoding: unicode
  database: ubuntu